#!/bin/bash
# Cron wrapper for scripts/health_check.py.
#
# Cron runs with an empty environment (no PATH, no HOME-default shell
# config), so we set up the project paths explicitly. Sourcing .env
# pulls in HEALTH_CHECK_DISCORD_WEBHOOK_URL without committing it.
#
# Schedule: */5 * * * * /home/probius/collect_price_variable/scripts/health_check_wrapper.sh
# Logs:    appended to logs/health_check.log (cron stdout redirect).
set -euo pipefail

# Resolve repo root from this script's location so the wrapper is
# move-safe (works regardless of CWD when cron invokes it).
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# Load .env (no-op if missing) — `set -a` makes every assignment
# automatically exported, so the python child process inherits.
if [[ -f .env ]]; then
    set -a
    # shellcheck disable=SC1091  # .env is generated by the user, not in lint scope
    source .env
    set +a
fi

# Plain python3 (script uses stdlib only — no project venv needed,
# keeps the cron job decoupled from the .venv lifecycle).
exec python3 scripts/health_check.py
